apiVersion: batch/v1
kind: Job
metadata:
  name: nlp-train-job
spec:
  template:
    spec:
      containers:
      - name: nlp-pipeline
        image: nlp-ticket-classification-mlops:latest
        imagePullPolicy: Never
        # On donne un peu de souffle au container
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
      restartPolicy: Never
  backoffLimit: 2