apiVersion: batch/v1
kind: Job
metadata:
  name: nlp-train-job
spec:
  template:
    spec:
      containers:
      - name: nlp-train-container
        image: nlp-ticket-classification-mlops:latest
        imagePullPolicy: Never

        volumeMounts:
        - name: model-storage
          mountPath: /app/models  
       
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: nlp-model-pvc
      
      restartPolicy: Never